### ISSUE TITLE
rewrite in c# 

### ISSUE THREAD

**Issue by Torkilso** [havlan/Sokker#1]

**Comment by havlan** [comment]
@Torkilso you are very welcome to do so! I would need advanced performance metrics in order to decide which version to go for. Whats your argument for using C#? :+1: 
Added it to the 1.0.0 milestone!

**Comment by havlan** [comment]
@Torkilso I would prefer to rewrite it in OCaml or Elixir

**Comment by Torkilso** [comment]
I think Tjabe is a great candidate for writing this in C#, he's a real beast! He probably know more about it than me.

Writing it in Elixir is also a great idea! A docker container would also be smooth and really nice :100:

**Comment by havlan** [comment]
```
FROM scratch

ADD Horse Horse

ENV PORT 3000

EXPOSE 3000

CMD ["/Horse"]
```

Build an example app as Horse. And thats it I guess. The websocket should connect to the containers localhost env and not my host machine.

**Comment by Torkilso** [comment]
Wow that is genius Haavard :1st_place_medal: 

I found this, it is really neat:
http://horsejs.github.io/
